### ISSUE TITLE
label="",symbol="GAS"

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-exporter#118]
```
label="",symbol="GAS"
```

What's the reason for this garbage? I'm ok to have the ability to group labels, but not in this way.

**Comment by roman-khimov** [comment]
It'd be hard to find the reason if we don't know what's going on.

**Comment by 532910** [comment]
`curl -s localhost:16512/metrics | grep nep`
https://github.com/nspcc-dev/neo-exporter/blob/9740b918b66578246cc5a7e3df403adf880b4062/config/config.yaml#L28

**Comment by roman-khimov** [comment]
`symbol` just comes from the contract. But label should be respected. Right, @smallhive?

**Comment by smallhive** [comment]
label was added as an alternative to symbol. It may be used to give human readable value for unknown tokens

**Comment by roman-khimov** [comment]
IIUC @532910 has label configured, but not shown in metrics.

**Comment by smallhive** [comment]
Checked with default config.yaml, latest master
```
neofs_net_monitor_nep_17_balance{account="3c3f4b84773ef0141576e48c3ff60e5078235891",contract="d2a4cff31913016155e38e474a2c06d08be276cf",label="GAS",symbol="GAS"} 5508.93011
neofs_net_monitor_nep_17_balance{account="40cf93b32c0a328fe8eeae505099147a5adaf646",contract="ef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",label="neo",symbol="NEO"} 0
neofs_net_monitor_nep_17_balance{account="653d7796269ebfa14b632f9a7f09560868d9f646",contract="ef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",label="neo",symbol="NEO"} 0
```

**Comment by roman-khimov** [comment]
I've checked with a different label, works for me as well.

**Comment by 532910** [comment]
1. I'm not going to set `label` in the config. What the hell empty label is shown? I have not  asked for it!
2. What is the reason for such a custom label? I believe label `label` should be completely removed.

**Comment by roman-khimov** [comment]
So basically what you want is to not have `label` when it's not specified in the config?
